export const BUZZ_INIT_STARTED = "BUZZ_INIT_STARTED";
export const BUZZ_INIT_SUCCESS = "BUZZ_INIT_SUCCESS";
export const BUZZ_INIT_FAILED = "BUZZ_INIT_FAILED";

export const LOAD_MORE_BUZZ_STARTED = "LOAD_MORE_BUZZ_STARTED";
export const LOAD_MORE_BUZZ_SUCCESS = "LOAD_MORE_BUZZ_SUCCESS";
export const LOAD_MORE_BUZZ_FAILED = "LOAD_MORE_BUZZ_FAILED";

export const REACTION_UPDATE_STARTED = "REACTION_UPDATE_STARTED";
export const REACTION_SET_SUCCESS = "REACTION_SET_SUCCESS";
export const REACTION_UNSET_SUCCESS = "REACTION_UNSET_SUCCESS";
export const REACTION_UPDATE_SUCCESS = "REACTION_UPDATE_SUCCESS";
export const REACTION_UPDATE_FAILED = "REACTION_UPDATE_FAILED";

export const SET_BUZZ_STATUS_DEFAULT = "SET_BUZZ_STATUS_DEFAULT";

export const UPDATE_LOAD_MORE = "UPDATE_LOAD_MORE";

export const BUZZ_UPDATE_STARTED = "BUZZ_UPDATE_STARTED";
export const BUZZ_UPDATE_SUCCESS = "BUZZ_UPDATE_SUCCESS";
export const BUZZ_UPDATE_FAILED = "BUZZ_UPDATE_FAILED";

export const REPORT_BUZZ_STARTED = "REPORT_BUZZ_STARTED";
export const REPORT_BUZZ_SUCCESS = "REPORT_BUZZ_SUCCESS";
export const REPORT_BUZZ_FAILED = "REPORT_BUZZ_FAILED";

export const CREATE_BUZZ_STARTED = "CREATE_BUZZ_STARTED";
export const CREATE_BUZZ_SUCCESS = "CREATE_BUZZ_SUCCESS";
export const CREATE_BUZZ_FAILED = "CREATE_BUZZ_FAILED";
