export const INIT_COMPLAINT_STARTED = "INIT_COMPLAINT_STARTED";
export const INIT_COMPLAINT_SUCCESS = "INIT_COMPLAINT_SUCCESS";
export const INIT_COMPLAINT_FAILED = "INIT_COMPLAINT_FAILED";

export const ADD_COMPLAINT_STARTED = "ADD_COMPLAINT_STARTED";
export const ADD_COMPLAINT_SUCCESS = "ADD_COMPLAINT_SUCCESS";
export const ADD_COMPLAINT_FAILED = "ADD_COMPLAINT_FAILED";

export const SET_COMPLAINT_STATUS_DEFAULT = "SET_COMPLAINT_STATUS_DEFAULT";
