export const USER_LOGIN_STARTED = "USER_LOGIN_STARTED";
export const USER_LOGIN_SUCCESS = "USER_LOGIN_SUCCESS";
export const USER_LOGIN_FAILED = "USER_LOGIN_FAILED";

export const USER_LOGOUT_STARTED = "USER_LOGOUT_STARTED";
export const USER_LOGOUT_SUCCESS = "USER_LOGOUT_SUCCESS";
export const USER_LOGOUT_FAILED = "USER_LOGOUT_FAILED";

export const CHANGE_PROFILE_STARTED = "CHANGE_PROFILE_STARTED";
export const CHANGE_PROFILE_SUCCESS = "CHANGE_PROFILE_SUCCESS";
export const CHANGE_PROFILE_FAILED = "CHANGE_PROFILE_FAILED";

export const STATUS = {
    SUCCESS: 'SUCCESS',
    STARTED: 'STARTED',
    FAILED: 'FAILED',
    DEFAULT: 'DEFAULT'
}