export const USER_LOGIN_STARTED = "USER_LOGIN_STARTED";
export const USER_LOGIN_SUCCESS = "USER_LOGIN_SUCCESS";
export const USER_LOGIN_FAILED = "USER_LOGIN_FAILED";

export const USER_LOGOUT_STARTED = "USER_LOGOUT_STARTED";
export const USER_LOGOUT_SUCCESS = "USER_LOGOUT_SUCCESS";
export const USER_LOGOUT_FAILED = "USER_LOGOUT_FAILED";

export const CHANGE_PROFILE_STARTED = "CHANGE_PROFILE_STARTED";
export const CHANGE_PROFILE_SUCCESS = "CHANGE_PROFILE_SUCCESS";
export const CHANGE_PROFILE_FAILED = "CHANGE_PROFILE_FAILED";

export const BUZZ_INIT_STARTED = "BUZZ_INIT_STARTED";
export const BUZZ_INIT_SUCCESS = "BUZZ_INIT_SUCCESS";
export const BUZZ_INIT_FAILED = "BUZZ_INIT_FAILED";

export const LOAD_MORE_BUZZ_STARTED = "LOAD_MORE_BUZZ_STARTED";
export const LOAD_MORE_BUZZ_SUCCESS = "LOAD_MORE_BUZZ_SUCCESS";
export const LOAD_MORE_BUZZ_FAILED = "LOAD_MORE_BUZZ_FAILED";

export const REACTION_UPDATE_STARTED = "REACTION_UPDATE_STARTED";
export const REACTION_SET_SUCCESS = "REACTION_SET_SUCCESS";
export const REACTION_UNSET_SUCCESS = "REACTION_UNSET_SUCCESS";
export const REACTION_UPDATE_SUCCESS = "REACTION_UPDATE_SUCCESS";
export const REACTION_UPDATE_FAILED = "REACTION_UPDATE_FAILED";

export const SET_BUZZ_STATUS_DEFAULT = "SET_BUZZ_STATUS_DEFAULT";

export const UPDATE_LOAD_MORE = "UPDATE_LOAD_MORE";

export const BUZZ_UPDATE_STARTED = "BUZZ_UPDATE_STARTED";
export const BUZZ_UPDATE_SUCCESS = "BUZZ_UPDATE_SUCCESS";
export const BUZZ_UPDATE_FAILED = "BUZZ_UPDATE_FAILED";

export const REPORT_BUZZ_STARTED = "REPORT_BUZZ_STARTED";
export const REPORT_BUZZ_SUCCESS = "REPORT_BUZZ_SUCCESS";
export const REPORT_BUZZ_FAILED = "REPORT_BUZZ_FAILED";

export const STATUS = {
    SUCCESS: 'SUCCESS',
    STARTED: 'STARTED',
    FAILED: 'FAILED',
    DEFAULT: 'DEFAULT'
};

export const REACTION = {
    ANGRY: 'angry',
    HAPPY: 'happy',
    SAD: 'sad'
};