export const GET_MY_RESOLVE_STARTED = "GET_MY_RESOLVE_STARTED";
export const GET_MY_RESOLVE_SUCCESS = "GET_MY_RESOLVE_SUCCESS";
export const GET_MY_RESOLVE_FAILED = "GET_MY_RESOLVE_FAILED";

export const INIT_ALL_COMPLAINTS_STARTED = "INIT_ALL_COMPLAINTS_STARTED";
export const INIT_ALL_COMPLAINTS_SUCCESS = "INIT_ALL_COMPLAINTS_SUCCESS";
export const INIT_ALL_COMPLAINTS_FAILED = "INIT_ALL_COMPLAINTS_FAILED";

export const UPDATE_COMPLAINT_STATUS_STARTED = "UPDATE_COMPLAINT_STATUS_STARTED";
export const UPDATE_COMPLAINT_STATUS_SUCCESS = "UPDATE_COMPLAINT_STATUS_SUCCESS";
export const UPDATE_COMPLAINT_STATUS_FAILED = "UPDATE_COMPLAINT_STATUS_FAILED";

export const ASSIGN_RESOLVE_STARTED = "ASSIGN_RESOLVE_STARTED";
export const ASSIGN_RESOLVE_SUCCESS = "ASSIGN_RESOLVE_SUCCESS";
export const ASSIGN_RESOLVE_FAILED = "ASSIGN_RESOLVE_FAILED";


export const SET_RESOLVE_STATUS_DEFAULT = "SET_RESOLVE_STATUS_DEFAULT";