export const CHANGE_PROFILE_IMAGE_STARTED = "CHANGE_PROFILE_IMAGE_STARTED";
export const CHANGE_PROFILE_IMAGE_SUCCESS = "CHANGE_PROFILE_IMAGE_SUCCESS";
export const CHANGE_PROFILE_IMAGE_FAILED = "CHANGE_PROFILE_IMAGE_FAILED";

export const FETCH_ALL_USERS_STARTED = "FETCH_ALL_USERS_STARTED";
export const FETCH_ALL_USERS_SUCCESS = "FETCH_ALL_USERS_SUCCESS";
export const FETCH_ALL_USERS_FAILED = "FETCH_ALL_USERS_FAILED";
