export const CHANGE_PROFILE_IMAGE_STARTED = "CHANGE_PROFILE_IMAGE_STARTED";
export const CHANGE_PROFILE_IMAGE_SUCCESS = "CHANGE_PROFILE_IMAGE_SUCCESS";
export const CHANGE_PROFILE_IMAGE_FAILED = "CHANGE_PROFILE_IMAGE_FAILED";
