export const CHANGE_PROFILE_IMAGE_STARTED = "CHANGE_PROFILE_IMAGE_STARTED";
export const CHANGE_PROFILE_IMAGE_SUCCESS = "CHANGE_PROFILE_IMAGE_SUCCESS";
export const CHANGE_PROFILE_IMAGE_FAILED = "CHANGE_PROFILE_IMAGE_FAILED";

export const USER_STATUSES = {
    ACTIVE: 'Active',
    DEACTIVE: 'Deactive'
};

export const USER_ROLES = {
    SUPER_ADMIN: 'Super Admin',
    ADMIN: 'Admin',
    USER: 'User'
};